import { useState } from 'react';
import './platform.css';

const art = (name: string) => `${import.meta.env.BASE_URL}assets/sprites/food-${name}.svg`;
const foods = ['baursak','tea','kurt','samsa','kazy','zhent'];

export function Landing() {
  const [guests,setGuests] = useState(100);
  const [participation,setParticipation] = useState(30);
  const [cost,setCost] = useState(350);
  const rewards = Math.round(guests * participation / 100);
  return <div className="promo">
    <header className="promo-nav"><a className="promo-brand" href="#home"><span>✳</span> DASTAKHAN<small>FOR CAFÉS</small></a><nav><a href="#how" onClick={e=>{e.preventDefault();document.getElementById('how')?.scrollIntoView({behavior:'smooth'});}}>Как это работает</a><a className="promo-nav-demo" href="#demo">Кабинет кафе <span>↗</span></a></nav></header>
    <main>
      <section className="promo-hero">
        <div className="promo-intro"><div className="promo-eyebrow"><span/> МАЛЕНЬКАЯ ИГРА. ТЁПЛЫЕ ОТНОШЕНИЯ.</div><h1>Пока готовится заказ,<br/><em>рождается повод</em><br/>вернуться.</h1><p>Превратите ожидание в удовольствие: гости собирают угощения, открывают награды из вашего меню и возвращаются за новым впечатлением.</p><div className="promo-actions"><a className="promo-primary" href="#guest">Попробовать как гость <span>↗</span></a><a className="promo-secondary" href="#demo">Я владелец кафе →</a></div><div className="promo-note">Без установки приложения · Ваше меню · Ваши правила</div></div>
        <div className="promo-scene" aria-label="Пример игровой страницы кафе"><div className="promo-orbit"/><span className="promo-scene-label">ОЖИДАНИЕ С ХОРОШИМ ПОСЛЕВКУСИЕМ</span><img className="promo-food floating-one" src={art('baursak')} alt=""/><img className="promo-food floating-two" src={art('tea')} alt=""/><div className="promo-phone"><div className="promo-island"/><div className="promo-phone-head"><span>✳</span><div>Кафе «Тары»<small>Демонстрационное кафе</small></div><span>•••</span></div><h2>Соберите свой<br/>вкусный момент.</h2><div className="promo-game-hud"><span>Цель <b>25 баурсаков</b></span><span>Ходы <b>20</b></span></div><div className="promo-mini-board">{Array.from({length:49},(_,i)=><img key={i} src={art(foods[(i*3+Math.floor(i/7)*2+i%3)%6])} alt=""/>)}</div><div className="promo-phone-prize"><span>✧</span><div>Чай за вашу победу<small>Скидка сейчас или подарок в следующий визит</small></div></div><a href="#guest" className="promo-phone-cta">Открыть настоящее демо →</a><small className="promo-mock-note">Иллюстрация · В игре поле 11 × 11</small></div><div className="promo-ticket"><span>ВАШ СЛЕДУЮЩИЙ ВИЗИТ</span><strong>С приятным<br/>дополнением.</strong><div>✧ Подарок из меню</div></div></div>
      </section>
      <div className="promo-strip"><span>01 / ГОСТЬ ИГРАЕТ</span><i>✳</i><span>02 / КАФЕ УГОЩАЕТ</span><i>✳</i><span>03 / ПОЯВЛЯЕТСЯ ПОВОД ВЕРНУТЬСЯ</span></div>
      <section id="how" className="promo-section"><div className="promo-section-heading"><span className="promo-eyebrow">ОТ ПЕРВОГО КАСАНИЯ ДО НОВОЙ ВСТРЕЧИ</span><h2>Всё начинается<br/>за вашим столиком.</h2><p>Короткий и понятный путь гостя. Без регистрации перед первой игрой и без сложного обучения.</p></div><div className="promo-steps">{[['01','Открыл страницу','Гость сканирует QR на столе и видит ваше кафе, меню и условия награды.'],['02','Сыграл партию','Собирает казахские угощения в «три в ряд», пока кухня готовит заказ.'],['03','Выбрал награду','Скидка 50% на призовое блюдо сейчас или это блюдо в подарок при следующем визите.']].map(([n,title,body])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
      <section className="promo-owner"><div><span className="promo-eyebrow">ГОСТЕПРИИМСТВО ПОД ВАШИМ БРЕНДОМ</span><h2>Ваше кафе.<br/>Ваши угощения.<br/><em>Ваш контроль.</em></h2><p>Вы выбираете блюда, задаёте условия и ограничиваете количество наград. Сотрудник проверяет купон и отмечает выдачу.</p><a className="promo-primary" href="#demo">Настроить демокафе <span>↗</span></a></div><div className="promo-owner-preview"><div className="promo-window-top"><span>✳ Тары / Управление</span><span>ДЕМО</span></div><h3>Сегодня угощаем</h3><div className="promo-menu-row"><img src={art('tea')} alt="Пиала чая"/><div><b>Чай по-казахски</b><small>Подарок к следующему визиту</small></div><span>Активно</span></div><div className="promo-menu-row"><img src={art('baursak')} alt="Баурсаки"/><div><b>Баурсаки с каймаком</b><small>50% на блюдо сегодня</small></div><span>Активно</span></div><div className="promo-preview-budget"><span>Вы устанавливаете лимит</span><strong>Ни одного<br/>неожиданного угощения.</strong></div><small>Пример интерфейса. Реальные лимиты и погашения требуют серверного запуска.</small></div></section>
      <section className="promo-section promo-economics"><div><span className="promo-eyebrow">НАЧНИТЕ С НЕБОЛЬШОГО ПИЛОТА</span><h2>Сначала считаем.<br/>Потом угощаем.</h2><p>Оцените расходы на подарки. Это сценарный расчёт, а не прогноз продаж или обещание роста лояльности.</p></div><div className="promo-calculator"><label>Гостей в день <b>{guests}</b><input type="range" min="20" max="500" step="10" value={guests} onChange={e=>setGuests(+e.target.value)}/></label><label>Доля гостей, получивших подарок <b>{participation}%</b><input type="range" min="5" max="100" step="5" value={participation} onChange={e=>setParticipation(+e.target.value)}/></label><label>Себестоимость подарка, ₸<input type="number" min="0" max="100000" value={cost} onChange={e=>setCost(Math.max(0,Math.min(100000,Number(e.target.value))))}/></label><div className="promo-calc-total"><span>При выдаче всех {rewards} подарков в день</span><strong>{(rewards*cost).toLocaleString('ru-RU')} ₸</strong><small>Без подписки, интеграций и прочих расходов. Для скидки вместо себестоимости учитывайте потерю выручки.</small></div></div></section>
      <section className="promo-faq"><h2>Перед первым запуском</h2>{[['Это уже готовая система выдачи призов?','Сейчас доступно интерактивное демо: настройка кафе, меню, игра и тестовые купоны. Данные сохраняются только в этом браузере. Для реального кафе нужен сервер и защищённый доступ сотрудников.'],['Можно ли компенсировать половину всего счёта?','В текущем сценарии скидка 50% относится только к призовому блюду. Скидку на весь чек следует запускать отдельно, с верхним пределом и согласованной экономикой.'],['Как понять, приносит ли игра пользу?','На пилоте сравниваем участие, погашенные награды, повторные визиты и расходы. Рост выручки и лояльности нужно измерить, а не обещать заранее.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
      <section className="promo-final"><span>ДАВАЙТЕ СДЕЛАЕМ ОЖИДАНИЕ ВКУСНЕЕ</span><h2>Первую партию<br/>подаём прямо сейчас.</h2><a href="#guest" className="promo-primary">Начать знакомство <span>↗</span></a></section>
    </main><footer className="promo-footer"><a href="#home" className="promo-brand">✳ DASTAKHAN</a><span>Игра со вкусом. Создана для гостеприимства.</span><a href="#demo">Демонстрационный кабинет ↗</a></footer>
  </div>;
}
