import { useEffect, useState } from 'react';
import './cafe.css';
import { quoteReward, redeemReward, type Reward } from '../../../../packages/rewards/src/index.ts';

type Dish = { id: string; name: string; description: string; price: number; active: boolean };
type Coupon = { id: string; dish: string; dishId: string; priceMinor: number; value: number; mode: 'now' | 'next'; used: boolean; issued: number };
type Demo = { name: string; description: string; image: string; menu: Dish[]; budget: number; limit: number; enabled: boolean; coupons: Coupon[] };
type Section = 'overview' | 'menu' | 'campaign' | 'brand' | 'coupons';
const KEY = 'dastakhan.cafe-demo.v2';
const seed = (): Demo => ({ name: 'Кафе «Тары»', description: 'Знакомые вкусы. Новые поводы встретиться.', image: '', budget: 30000, limit: 20, enabled: true, coupons: [], menu: [
  { id: 'baursak', name: 'Баурсаки', description: 'Тёплые, воздушные. Подаём с каймаком.', price: 1200, active: true },
  { id: 'tea', name: 'Чай по-казахски', description: 'Чёрный чай, молоко и немного уюта.', price: 900, active: true },
  { id: 'samsa', name: 'Самса из печи', description: 'Сочная начинка и хрустящее тесто.', price: 1100, active: true },
  { id: 'kazy', name: 'Казы', description: 'Традиционный вкус, современная подача.', price: 2900, active: true },
  { id: 'manty', name: 'Манты', description: 'Ручная лепка, говядина и пряности.', price: 2400, active: true },
  { id: 'zhent', name: 'Жент', description: 'Нежный десерт к вашей пиале чая.', price: 800, active: true },
] });
export function recordCafeGameWin(detail: { levelId: string; score: number; movesLeft: number }) {
  try { sessionStorage.setItem('dastakhan.cafe-win', JSON.stringify(detail)); } catch { /* The demonstration still works without storage. */ }
}
const money = (value: number) => `${value.toLocaleString('ru-RU')} ₸`;
const sprite = (id: string) => `${import.meta.env.BASE_URL}assets/sprites/food-${id}.svg`;
function load(): Demo { try { const value = JSON.parse(localStorage.getItem(KEY) ?? 'null') as Demo | null; return value && Array.isArray(value.menu) && Array.isArray(value.coupons) && typeof value.name === 'string' ? value : seed(); } catch { return seed(); } }
const nav: [Section, string, string][] = [['overview', 'Обзор', '◈'], ['menu', 'Меню', '▤'], ['campaign', 'Награды', '✧'], ['coupons', 'Купоны', '▧'], ['brand', 'Ваше кафе', '⌂']];

export default function CafeApp({ onPlay }: { onPlay: () => void }) {
  const [data, setData] = useState<Demo>(load);
  const [section, setSection] = useState<Section>('overview');
  const [guest, setGuest] = useState(location.hash.startsWith('#guest'));
  const [notice, setNotice] = useState('');
  const [dishId, setDishId] = useState('baursak');
  const [mode, setMode] = useState<'now' | 'next'>('now');
  const [code, setCode] = useState('');
  const [resetOpen, setResetOpen] = useState(false);
  const [laterVisit, setLaterVisit] = useState(false);
  const [gameWin, setGameWin] = useState(() => { try { return Boolean(sessionStorage.getItem('dastakhan.cafe-win')); } catch { return false; } });
  useEffect(() => { try { localStorage.setItem(KEY, JSON.stringify(data)); } catch { setNotice('Не удалось сохранить настройки в этом браузере.'); } }, [data]);
  useEffect(() => { const sync = () => setGuest(location.hash.startsWith('#guest')); window.addEventListener('hashchange', sync); return () => window.removeEventListener('hashchange', sync); }, []);
  const activeMenu = data.menu.filter(dish => dish.active);
  const selected = activeMenu.find(dish => dish.id === dishId) ?? activeMenu[0];
  const reserved = data.coupons.reduce((sum, coupon) => sum + coupon.value, 0);
  const redeemed = data.coupons.filter(coupon => coupon.used).length;
  const cost = selected ? quoteReward(Math.round(selected.price * 100), mode === 'now' ? 'half_now' : 'free_next_visit').discountMinor / 100 : 0;
  const remaining = Math.max(0, data.budget - reserved);
  const issueAllowed = Boolean(selected && data.enabled && data.coupons.length < data.limit && cost <= remaining);
  function patch(changes: Partial<Demo>) { setData(previous => ({ ...previous, ...changes })); }
  function showGuest(value: boolean) { location.hash = value ? 'guest' : 'demo'; setGuest(value); setNotice(''); }
  async function copyLink() { try { await navigator.clipboard.writeText(`${location.href.split('#')[0]}#guest`); setNotice('Ссылка скопирована. Настройки демо доступны только в этом браузере.'); } catch { setNotice(`Ссылка гостя: ${location.href.split('#')[0]}#guest`); } }
  function issue() {
    if (!issueAllowed || !selected) return;
    const coupon: Coupon = { id: `DEMO-${crypto.randomUUID().slice(0, 8).toUpperCase()}`, dish: selected.name, dishId: selected.id, priceMinor: Math.round(selected.price * 100), value: cost, mode, used: false, issued: Date.now() };
    setGameWin(false); try { sessionStorage.removeItem('dastakhan.cafe-win'); } catch { /* Demo storage is optional. */ }
    patch({ coupons: [coupon, ...data.coupons] }); setCode(coupon.id); setNotice('Тестовый купон создан. Он не даёт права на получение блюда.');
  }
  function redeem() {
    const coupon = data.coupons.find(item => item.id === code.trim().toUpperCase());
    if (!coupon) { setNotice('Купон не найден. Скопируйте код из списка ниже.'); return; }
    if (coupon.used) { setNotice('Этот купон уже погашен. Повторное погашение заблокировано в демо.'); return; }
    const reward: Reward = { id: coupon.id, tenantId: 'demo-cafe', guestId: 'demo-guest', dishId: coupon.dishId, sourceOrderId: 'demo-current-order', choice: coupon.mode === 'now' ? 'half_now' : 'free_next_visit', status: coupon.used ? 'redeemed' : 'available', issuedAt: coupon.issued, expiresAt: coupon.issued + 30 * 86400000, priceMinor: coupon.priceMinor };
    const result = redeemReward(reward, { tenantId: 'demo-cafe', guestId: 'demo-guest', orderId: laterVisit ? 'demo-next-order' : 'demo-current-order', orderOpenedAt: laterVisit ? Date.now() : coupon.issued - 1, now: Date.now(), dishAvailable: data.menu.some(dish => dish.id === coupon.dishId && dish.active) });
    if (!result.ok) { setNotice(result.reason === 'next_visit_required' ? 'Этот купон действует только в следующий визит. Включите симуляцию нового визита.' : result.reason === 'current_order_required' ? 'Скидка 50% действует на текущий заказ. Выключите симуляцию нового визита.' : result.reason === 'dish_unavailable' ? 'Блюдо сейчас недоступно в меню. Возобновите доступность для погашения.' : 'Купон недоступен или срок 30 дней истёк.'); return; }
    patch({ coupons: data.coupons.map(item => item.id === coupon.id ? { ...item, used: true } : item) }); setNotice(`Тестовый купон ${coupon.id} погашен.`);
  }
  function upload(file: File | undefined) {
    if (!file) return;
    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 1500000) { setNotice('Выберите JPG, PNG или WebP до 1,5 МБ.'); return; }
    const reader = new FileReader(); reader.onload = () => { patch({ image: String(reader.result) }); setNotice('Фото обновлено в гостевом меню.'); }; reader.readAsDataURL(file);
  }
  const restaurantArt = <div className="cf-food-art" aria-hidden="true">{['baursak', 'tea', 'kazy'].map(id => <img key={id} src={sprite(id)} alt="" />)}</div>;
  const coupons = <div className="cf-coupon-list">{data.coupons.length === 0 ? <div className="cf-empty"><span>✧</span><h3>Первый повод вернуться</h3><p>Создайте тестовый купон в режиме гостя. Здесь появится его статус.</p><button className="cf-btn cf-secondary" onClick={() => showGuest(true)}>Открыть гостевой экран ↗</button></div> : data.coupons.map(coupon => <article className="cf-coupon" key={coupon.id}><div><small>{coupon.mode === 'now' ? '−50% НА БЛЮДО СЕЙЧАС' : 'БЛЮДО В СЛЕДУЮЩИЙ ВИЗИТ'}</small><h3>{coupon.dish}</h3><button className="cf-code" onClick={() => { setCode(coupon.id); setNotice('Код подставлен в поле погашения.'); }}>{coupon.id}</button><p>Тестовый · {money(coupon.value)} · до {new Date(coupon.issued + 30 * 86400000).toLocaleDateString('ru-RU')}</p></div><span className={`cf-status ${coupon.used ? 'used' : ''}`}>{coupon.used ? 'Погашен' : 'Доступен'}</span></article>)}</div>;

  return <div className={`cf-app ${guest ? 'cf-is-guest' : ''}`}>
    <aside className="cf-sidebar"><a className="cf-wordmark" href="#home">DASTAKHAN<span>FOR CAFÉS</span></a><span className="cf-workspace-label">ВАШЕ ПРОСТРАНСТВО</span><div className="cf-workspace"><span className="cf-avatar">{data.name.replace(/^Кафе [«"]?/, '').charAt(0) || 'Т'}</span><div><strong>{data.name}</strong><small>Демонстрационное кафе</small></div></div><nav aria-label="Кабинет кафе">{nav.map(([id, label, icon]) => <button className={!guest && section === id ? 'active' : ''} onClick={() => { setSection(id); showGuest(false); }} key={id}><span>{icon}</span>{label}</button>)}</nav><div className="cf-sidebar-bottom"><p>Посмотрите на ваше кафе<br />глазами гостя.</p><button className="cf-btn cf-secondary" onClick={() => showGuest(true)}>Гостевой экран ↗</button><a href="#home">← На промосайт</a></div></aside>
    <main className="cf-main"><header className="cf-topbar"><span>Рабочее пространство <b>/ {guest ? 'Гостевой экран' : nav.find(item => item[0] === section)?.[1]}</b></span><span className="cf-demo-pill"><i /> ДЕМО</span></header>
      <div className="cf-mobile-nav"><a href="#home">DASTAKHAN</a><button onClick={() => showGuest(!guest)}>{guest ? 'Кабинет кафе' : 'Я гость'} ↗</button></div>
      {!guest && <nav className="cf-tabs" aria-label="Разделы">{nav.map(([id, label]) => <button key={id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}>{label}</button>)}</nav>}
      <div className="cf-content">
      <div className="cf-demo-note">Демонстрационный режим · данные сохраняются в этом браузере · реальные призы не выдаются</div>
      {notice && <div className="cf-notice" role="status"><span>{notice}</span><button aria-label="Закрыть уведомление" onClick={() => setNotice('')}>×</button></div>}
      {guest ? <div className="cf-guest-layout"><section className="cf-guest-main"><div className="cf-restaurant-hero">{data.image ? <img className="cf-restaurant-photo" src={data.image} alt={data.name} /> : restaurantArt}<div><span className="cf-eyebrow">С ВКУСОМ К ВАШЕМУ ВИЗИТУ</span><h1>{data.name}</h1><p>{data.description}</p></div></div><section className="cf-play-card"><div><span className="cf-eyebrow">ПОКА ГОТОВИТСЯ ВАШ ЗАКАЗ</span><h2>Пара ходов.<br />Ещё один приятный момент.</h2><p>Собирайте угощения в игре «три в ряд».</p><button className="cf-btn" onClick={onPlay}>Начать игру <span>↗</span></button></div><img src={`${import.meta.env.BASE_URL}assets/sprites/special-ram.svg`} alt="Золотой барашек — игровой бонус" /></section><div className="cf-section-title"><h2>Меню для хорошего настроения</h2><span>{activeMenu.length} блюд</span></div><div className="cf-dish-grid">{activeMenu.map(dish => <article className="cf-dish" key={dish.id}><div className="cf-dish-image"><img src={sprite(dish.id)} alt={dish.name} /></div><h3>{dish.name}</h3><p>{dish.description}</p><strong>{money(dish.price)}</strong></article>)}</div></section><aside className="cf-guest-rewards"><div className="cf-card"><span className="cf-eyebrow">ПОПРОБУЙТЕ СЦЕНАРИЙ</span><h2>Ваш приятный бонус</h2><p>{gameWin ? 'Уровень пройден! Выберите демонстрационную награду. Результат проверен только в браузере.' : 'Кнопка ниже отдельно симулирует награду для презентации. Реальные призы не выдаются.'}</p><label className="cf-field">Выберите блюдо<select value={selected?.id ?? ''} onChange={event => setDishId(event.target.value)}>{activeMenu.map(dish => <option key={dish.id} value={dish.id}>{dish.name} · {money(dish.price)}</option>)}</select></label><div className="cf-reward-options"><button aria-pressed={mode === 'now'} className={mode === 'now' ? 'chosen' : ''} onClick={() => setMode('now')}><strong>−50% сейчас</strong><span>Только на выбранное блюдо.<br />Вы оплачиваете {money(selected ? quoteReward(Math.round(selected.price * 100), 'half_now').guestPaysMinor / 100 : 0)}.</span></button><button aria-pressed={mode === 'next'} className={mode === 'next' ? 'chosen' : ''} onClick={() => setMode('next')}><strong>Блюдо в подарок</strong><span>В следующий визит.<br />Без денежной выплаты.</span></button></div><button className="cf-btn cf-full" disabled={!issueAllowed} onClick={issue}>{gameWin ? 'Получить тестовый купон ✧' : 'Симулировать награду ✧'}</button>{!issueAllowed && <p className="cf-warning">{!data.enabled ? 'Выдача наград приостановлена.' : !selected ? 'Нет доступных блюд.' : 'Достигнут лимит купонов или бюджета.'}</p>}<small className="cf-fine">Один купон — одно применение. Демо не списывает оплату и не меняет ресторанный счёт.</small></div><div className="cf-section-title"><h2>Тестовые купоны</h2></div>{coupons}</aside></div> : <>
      <div className="cf-page-heading"><div><span className="cf-eyebrow">DASTAKHAN ДЛЯ ВАШЕГО КАФЕ</span><h1>{section === 'overview' ? 'Гости играют. Встречи продолжаются.' : section === 'menu' ? 'Ваше меню. Ваша история.' : section === 'campaign' ? 'Щедрость под контролем.' : section === 'brand' ? 'С характером вашего кафе.' : 'Каждый бонус на виду.'}</h1><p>{section === 'overview' ? 'Настройте маленький повод для большого возвращения.' : 'Все изменения доступны в гостевом экране этого браузера.'}</p></div><button className="cf-btn cf-secondary" onClick={() => showGuest(true)}>Как видит гость ↗</button></div>
      {section === 'overview' && <><div className="cf-overview-hero"><div><span className="cf-eyebrow">ВАШЕ КАФЕ В ИГРЕ</span><h2>Сделайте ожидание<br /><em>частью впечатления.</em></h2><p>Меню, любимая игра и комплимент от заведения — в одном гостевом экране.</p><button className="cf-btn cf-light" onClick={() => showGuest(true)}>Попробовать за гостя ↗</button></div>{restaurantArt}<span className="cf-hero-tag">Made for moments together</span></div><div className="cf-metrics"><article><span>Тестовых купонов</span><strong>{data.coupons.length}<small> / {data.limit}</small></strong><p>Выдано в этом браузере</p></article><article><span>Погашено</span><strong>{redeemed}</strong><p>Симуляция визита гостя</p></article><article><span>Доступный резерв</span><strong>{money(remaining)}</strong><p>Лимит {money(data.budget)} по цене меню</p></article></div><div className="cf-bottom-grid"><section className="cf-card"><div className="cf-section-title"><h2>Три шага до первого гостя</h2><span>01 — 03</span></div>{[['01', 'Добавьте характер', 'Название и фото вашего заведения', 'brand'], ['02', 'Выберите угощения', 'Меню и цены, которые видит гость', 'menu'], ['03', 'Задайте границы', 'Лимит купонов и резерв наград', 'campaign']].map(([num, title, subtitle, page]) => <button className="cf-step" key={num} onClick={() => setSection(page as Section)}><span>{num}</span><div><strong>{title}</strong><small>{subtitle}</small></div><b>↗</b></button>)}</section><section className="cf-card cf-sharing"><span className="cf-eyebrow">ПРИГЛАШЕНИЕ К СТОЛУ</span><h2>Гостевой экран<br />уже готов.</h2><p>Откройте демо или скопируйте ссылку. На другом устройстве будут исходные настройки: облако ещё не подключено.</p><button className="cf-btn" onClick={copyLink}>Скопировать ссылку ↗</button></section></div></>}
      {section === 'menu' && <section className="cf-card"><div className="cf-section-title"><h2>Блюда заведения</h2><span>Редактируется сразу</span></div><div className="cf-edit-menu">{data.menu.map(dish => <article key={dish.id}><img src={sprite(dish.id)} alt="" /><label className="cf-field">Название<input maxLength={50} value={dish.name} onChange={event => patch({ menu: data.menu.map(item => item.id === dish.id ? { ...item, name: event.target.value } : item) })} /></label><label className="cf-field">Цена, ₸<input type="number" min="100" max="100000" step="100" value={dish.price} onChange={event => patch({ menu: data.menu.map(item => item.id === dish.id ? { ...item, price: Math.min(100000, Math.max(100, Number(event.target.value))) } : item) })} /></label><label className="cf-checkbox"><input type="checkbox" checked={dish.active} onChange={event => patch({ menu: data.menu.map(item => item.id === dish.id ? { ...item, active: event.target.checked } : item) })} /> В меню</label></article>)}</div><p className="cf-fine">Иллюстрации — игровые ассеты. В боевом кабинете предусмотрены фотографии и отдельная себестоимость блюд.</p></section>}
      {section === 'campaign' && <div className="cf-bottom-grid"><section className="cf-card"><h2>Параметры наград</h2><p>Резерв рассчитывается по стоимости скидки или полной цене блюда. Уже выданные купоны сохраняют стоимость на момент выдачи.</p><label className="cf-field">Резерв на все тестовые купоны, ₸<input type="number" min={reserved} max="10000000" step="1000" value={data.budget} onChange={event => patch({ budget: Math.max(reserved, Math.min(10000000, Number(event.target.value))) })} /></label><label className="cf-field">Максимальное количество купонов<input type="number" min={data.coupons.length} max="1000" value={data.limit} onChange={event => patch({ limit: Math.max(data.coupons.length, Math.min(1000, Math.floor(Number(event.target.value)))) })} /></label><label className="cf-toggle"><span><strong>Выдача наград</strong><small>{data.enabled ? 'Гости могут создавать тестовые купоны' : 'На паузе'}</small></span><input type="checkbox" checked={data.enabled} onChange={event => patch({ enabled: event.target.checked })} /></label></section><section className="cf-card cf-rules"><span className="cf-eyebrow">ПОНЯТНО ГОСТЮ И КОМАНДЕ</span><h2>Два способа<br />сказать «спасибо».</h2><div><b>01</b><h3>Половина стоимости сейчас</h3><p>Скидка 50% на конкретное блюдо. Не на весь чек и без выплаты денег.</p></div><div><b>02</b><h3>Угощение в следующий визит</h3><p>Купон на выбранное блюдо. В демо следующий визит симулируется администратором.</p></div></section></div>}
      {section === 'brand' && <div className="cf-bottom-grid"><section className="cf-card"><h2>Профиль заведения</h2><label className="cf-field">Название кафе<input maxLength={60} value={data.name} onChange={event => patch({ name: event.target.value })} /></label><label className="cf-field">Короткое описание<textarea maxLength={150} value={data.description} onChange={event => patch({ description: event.target.value })} /></label><label className="cf-field">Фото заведения<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => upload(event.target.files?.[0])} /><small>JPG, PNG, WebP · до 1,5 МБ · хранится локально</small></label>{data.image && <button className="cf-text-btn" onClick={() => patch({ image: '' })}>Убрать фото</button>}<button className="cf-btn" onClick={() => showGuest(true)}>Посмотреть результат ↗</button></section><section className="cf-brand-preview">{data.image ? <img src={data.image} alt="Фото вашего кафе" /> : restaurantArt}<div><span className="cf-eyebrow">ВАШЕ ГОСТЕПРИИМСТВО — В ЦИФРЕ</span><h2>{data.name}</h2><p>{data.description}</p></div></section></div>}
      {section === 'coupons' && <><section className="cf-card cf-redeem"><div><h2>Погасить тестовый купон</h2><p>Проверьте сценарий кассира. Повторное погашение не допускается.</p></div><div><label className="cf-checkbox cf-visit"><input type="checkbox" checked={laterVisit} onChange={event => setLaterVisit(event.target.checked)} /> Симулировать следующий визит</label><form onSubmit={event => { event.preventDefault(); redeem(); }}><label className="cf-field">Код купона<input value={code} onChange={event => setCode(event.target.value)} placeholder="DEMO-XXXXXXXX" required /></label><button className="cf-btn" type="submit">Погасить</button></form></div></section>{coupons}<p className="cf-fine">Это локальная симуляция, не защищённый сервер. Нет кассовой интеграции, проверки заказа, аккаунтов или контроля другого устройства.</p></>}
      <footer className="cf-footer"><span>DASTAKHAN · ресторанное демо</span><button onClick={() => setResetOpen(true)}>Сбросить демо</button></footer>
      {resetOpen && <section className="cf-reset cf-card" role="alert"><h3>Начать демонстрацию заново?</h3><p>Настройки кафе и тестовые купоны будут удалены из этого браузера. Прогресс игры сохранится.</p><button className="cf-btn" onClick={() => { setData(seed()); setResetOpen(false); setNotice('Демо сброшено.'); }}>Сбросить данные</button><button className="cf-btn cf-secondary" onClick={() => setResetOpen(false)}>Отмена</button></section>}
      </>}
      </div>
    </main>
  </div>;
}
